/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppSoarRouteImport } from './routes/_app.soar'
import { Route as AppRulesRouteImport } from './routes/_app.rules'
import { Route as AppRealtimeRouteImport } from './routes/_app.realtime'
import { Route as AppPacksRouteImport } from './routes/_app.packs'
import { Route as AppOrgsRouteImport } from './routes/_app.orgs'
import { Route as AppIngestRouteImport } from './routes/_app.ingest'
import { Route as AppIncidentsRouteImport } from './routes/_app.incidents'
import { Route as AppHuntingRouteImport } from './routes/_app.hunting'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCopilotRouteImport } from './routes/_app.copilot'
import { Route as AppCollectorsRouteImport } from './routes/_app.collectors'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'
import { Route as AppIncidentsIncidentIdRouteImport } from './routes/_app.incidents.$incidentId'
import { Route as AppThreatHuntingTimelineIncidentIdRouteImport } from './routes/_app.threat-hunting.timeline.$incidentId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSoarRoute = AppSoarRouteImport.update({
  id: '/soar',
  path: '/soar',
  getParentRoute: () => AppRoute,
} as any)
const AppRulesRoute = AppRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppRoute,
} as any)
const AppRealtimeRoute = AppRealtimeRouteImport.update({
  id: '/realtime',
  path: '/realtime',
  getParentRoute: () => AppRoute,
} as any)
const AppPacksRoute = AppPacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgsRoute = AppOrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => AppRoute,
} as any)
const AppIngestRoute = AppIngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsRoute = AppIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AppRoute,
} as any)
const AppHuntingRoute = AppHuntingRouteImport.update({
  id: '/hunting',
  path: '/hunting',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCopilotRoute = AppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectorsRoute = AppCollectorsRouteImport.update({
  id: '/collectors',
  path: '/collectors',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsIncidentIdRoute = AppIncidentsIncidentIdRouteImport.update({
  id: '/$incidentId',
  path: '/$incidentId',
  getParentRoute: () => AppIncidentsRoute,
} as any)
const AppThreatHuntingTimelineIncidentIdRoute =
  AppThreatHuntingTimelineIncidentIdRouteImport.update({
    id: '/threat-hunting/timeline/$incidentId',
    path: '/threat-hunting/timeline/$incidentId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AppAlertsRoute
  '/collectors': typeof AppCollectorsRoute
  '/copilot': typeof AppCopilotRoute
  '/dashboard': typeof AppDashboardRoute
  '/hunting': typeof AppHuntingRoute
  '/incidents': typeof AppIncidentsRouteWithChildren
  '/ingest': typeof AppIngestRoute
  '/orgs': typeof AppOrgsRoute
  '/packs': typeof AppPacksRoute
  '/realtime': typeof AppRealtimeRoute
  '/rules': typeof AppRulesRoute
  '/soar': typeof AppSoarRoute
  '/users': typeof AppUsersRoute
  '/incidents/$incidentId': typeof AppIncidentsIncidentIdRoute
  '/threat-hunting/timeline/$incidentId': typeof AppThreatHuntingTimelineIncidentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AppAlertsRoute
  '/collectors': typeof AppCollectorsRoute
  '/copilot': typeof AppCopilotRoute
  '/dashboard': typeof AppDashboardRoute
  '/hunting': typeof AppHuntingRoute
  '/incidents': typeof AppIncidentsRouteWithChildren
  '/ingest': typeof AppIngestRoute
  '/orgs': typeof AppOrgsRoute
  '/packs': typeof AppPacksRoute
  '/realtime': typeof AppRealtimeRoute
  '/rules': typeof AppRulesRoute
  '/soar': typeof AppSoarRoute
  '/users': typeof AppUsersRoute
  '/incidents/$incidentId': typeof AppIncidentsIncidentIdRoute
  '/threat-hunting/timeline/$incidentId': typeof AppThreatHuntingTimelineIncidentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/collectors': typeof AppCollectorsRoute
  '/_app/copilot': typeof AppCopilotRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/hunting': typeof AppHuntingRoute
  '/_app/incidents': typeof AppIncidentsRouteWithChildren
  '/_app/ingest': typeof AppIngestRoute
  '/_app/orgs': typeof AppOrgsRoute
  '/_app/packs': typeof AppPacksRoute
  '/_app/realtime': typeof AppRealtimeRoute
  '/_app/rules': typeof AppRulesRoute
  '/_app/soar': typeof AppSoarRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/incidents/$incidentId': typeof AppIncidentsIncidentIdRoute
  '/_app/threat-hunting/timeline/$incidentId': typeof AppThreatHuntingTimelineIncidentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alerts'
    | '/collectors'
    | '/copilot'
    | '/dashboard'
    | '/hunting'
    | '/incidents'
    | '/ingest'
    | '/orgs'
    | '/packs'
    | '/realtime'
    | '/rules'
    | '/soar'
    | '/users'
    | '/incidents/$incidentId'
    | '/threat-hunting/timeline/$incidentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/alerts'
    | '/collectors'
    | '/copilot'
    | '/dashboard'
    | '/hunting'
    | '/incidents'
    | '/ingest'
    | '/orgs'
    | '/packs'
    | '/realtime'
    | '/rules'
    | '/soar'
    | '/users'
    | '/incidents/$incidentId'
    | '/threat-hunting/timeline/$incidentId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/alerts'
    | '/_app/collectors'
    | '/_app/copilot'
    | '/_app/dashboard'
    | '/_app/hunting'
    | '/_app/incidents'
    | '/_app/ingest'
    | '/_app/orgs'
    | '/_app/packs'
    | '/_app/realtime'
    | '/_app/rules'
    | '/_app/soar'
    | '/_app/users'
    | '/_app/incidents/$incidentId'
    | '/_app/threat-hunting/timeline/$incidentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/soar': {
      id: '/_app/soar'
      path: '/soar'
      fullPath: '/soar'
      preLoaderRoute: typeof AppSoarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rules': {
      id: '/_app/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AppRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/realtime': {
      id: '/_app/realtime'
      path: '/realtime'
      fullPath: '/realtime'
      preLoaderRoute: typeof AppRealtimeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/packs': {
      id: '/_app/packs'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof AppPacksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orgs': {
      id: '/_app/orgs'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof AppOrgsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ingest': {
      id: '/_app/ingest'
      path: '/ingest'
      fullPath: '/ingest'
      preLoaderRoute: typeof AppIngestRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incidents': {
      id: '/_app/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AppIncidentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hunting': {
      id: '/_app/hunting'
      path: '/hunting'
      fullPath: '/hunting'
      preLoaderRoute: typeof AppHuntingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/copilot': {
      id: '/_app/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof AppCopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collectors': {
      id: '/_app/collectors'
      path: '/collectors'
      fullPath: '/collectors'
      preLoaderRoute: typeof AppCollectorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incidents/$incidentId': {
      id: '/_app/incidents/$incidentId'
      path: '/$incidentId'
      fullPath: '/incidents/$incidentId'
      preLoaderRoute: typeof AppIncidentsIncidentIdRouteImport
      parentRoute: typeof AppIncidentsRoute
    }
    '/_app/threat-hunting/timeline/$incidentId': {
      id: '/_app/threat-hunting/timeline/$incidentId'
      path: '/threat-hunting/timeline/$incidentId'
      fullPath: '/threat-hunting/timeline/$incidentId'
      preLoaderRoute: typeof AppThreatHuntingTimelineIncidentIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppIncidentsRouteChildren {
  AppIncidentsIncidentIdRoute: typeof AppIncidentsIncidentIdRoute
}

const AppIncidentsRouteChildren: AppIncidentsRouteChildren = {
  AppIncidentsIncidentIdRoute: AppIncidentsIncidentIdRoute,
}

const AppIncidentsRouteWithChildren = AppIncidentsRoute._addFileChildren(
  AppIncidentsRouteChildren,
)

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppCollectorsRoute: typeof AppCollectorsRoute
  AppCopilotRoute: typeof AppCopilotRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHuntingRoute: typeof AppHuntingRoute
  AppIncidentsRoute: typeof AppIncidentsRouteWithChildren
  AppIngestRoute: typeof AppIngestRoute
  AppOrgsRoute: typeof AppOrgsRoute
  AppPacksRoute: typeof AppPacksRoute
  AppRealtimeRoute: typeof AppRealtimeRoute
  AppRulesRoute: typeof AppRulesRoute
  AppSoarRoute: typeof AppSoarRoute
  AppUsersRoute: typeof AppUsersRoute
  AppThreatHuntingTimelineIncidentIdRoute: typeof AppThreatHuntingTimelineIncidentIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppCollectorsRoute: AppCollectorsRoute,
  AppCopilotRoute: AppCopilotRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHuntingRoute: AppHuntingRoute,
  AppIncidentsRoute: AppIncidentsRouteWithChildren,
  AppIngestRoute: AppIngestRoute,
  AppOrgsRoute: AppOrgsRoute,
  AppPacksRoute: AppPacksRoute,
  AppRealtimeRoute: AppRealtimeRoute,
  AppRulesRoute: AppRulesRoute,
  AppSoarRoute: AppSoarRoute,
  AppUsersRoute: AppUsersRoute,
  AppThreatHuntingTimelineIncidentIdRoute:
    AppThreatHuntingTimelineIncidentIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
