/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppSoarRouteImport } from './routes/_app/soar'
import { Route as AppRealtimeRouteImport } from './routes/_app/realtime'
import { Route as AppOrganizationRouteImport } from './routes/_app/organization'
import { Route as AppIngestRouteImport } from './routes/_app/ingest'
import { Route as AppIncidentsRouteImport } from './routes/_app/incidents'
import { Route as AppHuntingRouteImport } from './routes/_app/hunting'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCopilotRouteImport } from './routes/_app/copilot'
import { Route as AppAlertsRouteImport } from './routes/_app/alerts'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSoarRoute = AppSoarRouteImport.update({
  id: '/soar',
  path: '/soar',
  getParentRoute: () => AppRoute,
} as any)
const AppRealtimeRoute = AppRealtimeRouteImport.update({
  id: '/realtime',
  path: '/realtime',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationRoute = AppOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppRoute,
} as any)
const AppIngestRoute = AppIngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsRoute = AppIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AppRoute,
} as any)
const AppHuntingRoute = AppHuntingRouteImport.update({
  id: '/hunting',
  path: '/hunting',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCopilotRoute = AppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AppAlertsRoute
  '/copilot': typeof AppCopilotRoute
  '/dashboard': typeof AppDashboardRoute
  '/hunting': typeof AppHuntingRoute
  '/incidents': typeof AppIncidentsRoute
  '/ingest': typeof AppIngestRoute
  '/organization': typeof AppOrganizationRoute
  '/realtime': typeof AppRealtimeRoute
  '/soar': typeof AppSoarRoute
  '/users': typeof AppUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AppAlertsRoute
  '/copilot': typeof AppCopilotRoute
  '/dashboard': typeof AppDashboardRoute
  '/hunting': typeof AppHuntingRoute
  '/incidents': typeof AppIncidentsRoute
  '/ingest': typeof AppIngestRoute
  '/organization': typeof AppOrganizationRoute
  '/realtime': typeof AppRealtimeRoute
  '/soar': typeof AppSoarRoute
  '/users': typeof AppUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/copilot': typeof AppCopilotRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/hunting': typeof AppHuntingRoute
  '/_app/incidents': typeof AppIncidentsRoute
  '/_app/ingest': typeof AppIngestRoute
  '/_app/organization': typeof AppOrganizationRoute
  '/_app/realtime': typeof AppRealtimeRoute
  '/_app/soar': typeof AppSoarRoute
  '/_app/users': typeof AppUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alerts'
    | '/copilot'
    | '/dashboard'
    | '/hunting'
    | '/incidents'
    | '/ingest'
    | '/organization'
    | '/realtime'
    | '/soar'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/alerts'
    | '/copilot'
    | '/dashboard'
    | '/hunting'
    | '/incidents'
    | '/ingest'
    | '/organization'
    | '/realtime'
    | '/soar'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/alerts'
    | '/_app/copilot'
    | '/_app/dashboard'
    | '/_app/hunting'
    | '/_app/incidents'
    | '/_app/ingest'
    | '/_app/organization'
    | '/_app/realtime'
    | '/_app/soar'
    | '/_app/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/soar': {
      id: '/_app/soar'
      path: '/soar'
      fullPath: '/soar'
      preLoaderRoute: typeof AppSoarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/realtime': {
      id: '/_app/realtime'
      path: '/realtime'
      fullPath: '/realtime'
      preLoaderRoute: typeof AppRealtimeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organization': {
      id: '/_app/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AppOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ingest': {
      id: '/_app/ingest'
      path: '/ingest'
      fullPath: '/ingest'
      preLoaderRoute: typeof AppIngestRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incidents': {
      id: '/_app/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AppIncidentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hunting': {
      id: '/_app/hunting'
      path: '/hunting'
      fullPath: '/hunting'
      preLoaderRoute: typeof AppHuntingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/copilot': {
      id: '/_app/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof AppCopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppCopilotRoute: typeof AppCopilotRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHuntingRoute: typeof AppHuntingRoute
  AppIncidentsRoute: typeof AppIncidentsRoute
  AppIngestRoute: typeof AppIngestRoute
  AppOrganizationRoute: typeof AppOrganizationRoute
  AppRealtimeRoute: typeof AppRealtimeRoute
  AppSoarRoute: typeof AppSoarRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppCopilotRoute: AppCopilotRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHuntingRoute: AppHuntingRoute,
  AppIncidentsRoute: AppIncidentsRoute,
  AppIngestRoute: AppIngestRoute,
  AppOrganizationRoute: AppOrganizationRoute,
  AppRealtimeRoute: AppRealtimeRoute,
  AppSoarRoute: AppSoarRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
