// Mock data fallback used when the backend is unreachable.
// This keeps the UI demo-able while preserving real API contracts.

export const MOCK = {
  stats: {
    totalAlerts: 12847,
    criticalAlerts: 23,
    openIncidents: 7,
    soarActions: 142,
    collectorsOnline: 8,
    collectorsTotal: 9,
  },
  alerts: Array.from({ length: 24 }).map((_, i) => ({
    id: `a-${1000 + i}`,
    title: [
      "Suspicious PowerShell execution",
      "Multiple failed logins from foreign IP",
      "Unusual outbound traffic to known C2",
      "Privilege escalation attempt",
      "Lateral movement via SMB",
      "DNS tunneling indicators",
    ][i % 6],
    severity: (["critical", "high", "medium", "low"] as const)[i % 4],
    mitre: {
      tactic: ["Execution", "Initial Access", "Command & Control", "Privilege Escalation"][i % 4],
      technique: `T10${50 + (i % 20)}`,
    },
    ip: `198.51.${(i * 7) % 255}.${(i * 13) % 255}`,
    source: ["EDR", "Firewall", "Cloudtrail", "Suricata", "Sysmon"][i % 5],
    rule: `rule_${100 + i}`,
    timestamp: new Date(Date.now() - i * 1000 * 60 * 7).toISOString(),
  })),
  incidents: Array.from({ length: 8 }).map((_, i) => ({
    id: `inc-${200 + i}`,
    title: [
      "Ransomware staging detected",
      "Insider data exfiltration",
      "Credential stuffing campaign",
      "Unauthorized cloud admin role",
      "Web shell on edge host",
      "Beaconing to TOR exit",
      "S3 bucket made public",
      "MFA bypass attempt",
    ][i],
    status: (["open", "investigating", "resolved", "closed"] as const)[i % 4],
    severity: (["critical", "high", "medium", "low"] as const)[i % 4],
    analyst: ["A. Chen", "M. Park", "J. Singh", "R. Ortiz", "—"][i % 5],
    alertId: `a-${1000 + i}`,
    updatedAt: new Date(Date.now() - i * 1000 * 60 * 60).toISOString(),
  })),
  soar: Array.from({ length: 10 }).map((_, i) => ({
    id: `act-${i}`,
    name: [
      "Block IP at firewall",
      "Isolate host",
      "Disable user",
      "Quarantine file",
      "Revoke session",
      "Notify on-call",
    ][i % 6],
    status: (["success", "running", "failed", "queued"] as const)[i % 4],
    target: `198.51.${i}.${i * 11}`,
    playbook: ["P-Block-C2", "P-Isolate-Host", "P-Account-Lockdown"][i % 3],
    timestamp: new Date(Date.now() - i * 60000).toISOString(),
  })),
  blockedIps: ["45.88.12.4", "103.45.22.118", "185.234.218.66", "91.219.236.198"],
  rules: Array.from({ length: 6 }).map((_, i) => ({
    id: `r-${i}`,
    name: [
      "PowerShell EncodedCommand",
      "Suspicious LSASS Access",
      "Brute Force SSH",
      "AWS Root Login",
      "Office Macro Spawn",
      "Scheduled Task Persistence",
    ][i],
    enabled: i % 3 !== 0,
    severity: (["critical", "high", "medium", "low"] as const)[i % 4],
    description: "Detects suspicious activity matching known TTPs.",
  })),
  packs: [
    { id: "p-1", name: "Sigma Core", rules: 320, enabled: true, version: "1.4.0" },
    { id: "p-2", name: "Cloud Security", rules: 84, enabled: true, version: "0.9.2" },
    { id: "p-3", name: "Windows Endpoint", rules: 142, enabled: false, version: "2.1.0" },
  ],
  collectors: [
    {
      id: "c-1",
      name: "edge-fw-01",
      status: "online",
      lastSeen: new Date(Date.now() - 30_000).toISOString(),
      kind: "firewall",
    },
    {
      id: "c-2",
      name: "k8s-prod",
      status: "online",
      lastSeen: new Date(Date.now() - 60_000).toISOString(),
      kind: "k8s",
    },
    {
      id: "c-3",
      name: "office-edr",
      status: "offline",
      lastSeen: new Date(Date.now() - 86_400_000).toISOString(),
      kind: "edr",
    },
  ],
  orgs: [
    { id: "o-1", name: "Acme Corp", users: 24, plan: "Enterprise" },
    { id: "o-2", name: "Globex", users: 8, plan: "Pro" },
  ],
  users: [
    { id: "u-1", name: "Alice Chen", email: "alice@acme.io", role: "Admin" },
    { id: "u-2", name: "Marco Park", email: "marco@acme.io", role: "Analyst" },
    { id: "u-3", name: "Jay Singh", email: "jay@acme.io", role: "Viewer" },
  ],
  mitreTactics: [
    { name: "Initial Access", count: 14 },
    { name: "Execution", count: 22 },
    { name: "Persistence", count: 9 },
    { name: "Privilege Esc.", count: 6 },
    { name: "Defense Evasion", count: 18 },
    { name: "Credential Access", count: 11 },
    { name: "Discovery", count: 7 },
    { name: "Lateral Movement", count: 4 },
    { name: "Collection", count: 5 },
    { name: "Exfiltration", count: 3 },
    { name: "Command & Control", count: 12 },
    { name: "Impact", count: 2 },
  ],
  campaigns: [
    { id: "tc-1", name: "APT-Mirage", actor: "FIN12", iocs: 184, severity: "critical" as const },
    { id: "tc-2", name: "RansomCloud", actor: "Unknown", iocs: 64, severity: "high" as const },
    { id: "tc-3", name: "DNS-Sweep", actor: "Scanner", iocs: 28, severity: "low" as const },
  ],
};
